name: Prettier
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
permissions: write-all
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actionsx/prettier@v2
              with:
                  args: --write .
