name: RouteTesting
on: [push, pull_request]
permissions: write-all
jobs: 
  route_tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.DB_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MONGO_INITDB_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mongosh command
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
      
      - name: Populate MongoDB
        run: node createDB/populateDB.js
      
      - name: Start Express Server
        run: |
          nohup npm run dev & echo $! > express.pid
          sleep 60
          npm run test:routes
      
      - name: Ensure server is stopped
        if: always()
        run: |
          kill $(cat express.pid)