name: UnitTesting
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/puppeteer/puppeteer:latest
    env:
      CLICK_DELAY: ${{ secrets.CLICK_DELAY }}
      SCRAPE_DELAY: ${{ secrets.SCRAPE_DELAY }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      HEADLESS: ${{ secrets.HEADLESS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: 'npm'
      - run: npm ci
      - run: npm run test